language: node_js
node_js:
  - 0.10
notifications:
  irc: irc.freenode.org#greenfinity
before_script:
  - export PATH="$PWD/node_modules/.bin:$PATH"
  - bower install
  - export DISPLAY=:99.0
  - echo 'Starting buster server...'
  - buster server &
  - sleep 5
  - echo 'Done.'
  - echo 'Starting xvfb for FF...'
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - echo 'Done.'
  - echo 'Starting phantomjs browser...'
  - phantomjs ./node_modules/buster/script/phantom.js &
  - echo 'Done.'
  - sleep 8
  - echo 'Starting firefox browser...'
  - firefox http://localhost:1111/capture &
  - sleep 8
  - echo 'Done.' 
script:
  - buster test